### ISSUE TITLE
Неочевидное название пакетлиста

### ISSUE THREAD

**Issue by wartur** [unisender-dev/php-api-wrapper#2]
Обычно предполагаешь, что название репы и есть название пакетлиста
В вашем случае
```
unisender-dev/php-api-wrapper
```

Реально же это
```
unisender/api-wrapper
```

Хотя бы в ридми напишите про это... а то люди будут завтыкать в это... сам потратил лишние пол минуты на разбор проблемы

**Comment by unisender-dev** [comment]
Обновили readme.md
