### ISSUE TITLE
Всегда ли обязательно требование ext-bz2?

### ISSUE THREAD

**Issue by antonkomarev** [unisender-dev/php-api-wrapper#8]
При попытке установить пакет получил сообщение:
> unisender/api-wrapper v1.6.1 requires ext-bz2

По факту же `bzip2` используется только при использовании компрессии (которая выключена по-умолчанию):

https://github.com/unisender-dev/php-api-wrapper/blob/0370d81c15579891996b4561b09f7550c60af119/UnisenderApi.php#L391-L397

Действительно ли необходимо требование `ext-bz2` или его можно перенести в список `suggest`?

Почему именно `bzip2` и можно ли использовать другие компрессоры? Если да, тогда bzip явно не обязательное требование.

**Comment by unisender-dev** [comment]
Добрый день. Спасибо что обратили внимание. Действительно ext-bz2 нужен только в suggest где он и находится. Из require уберем.

**Comment by unisender-dev** [comment]
done.
